source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '11.0'
use_frameworks!

target 'JVMenuPopover' do
  pod "JVMenuPopover", :path => "../"
  target 'Tests' do
    pod "JVMenuPopover", :path => "../"
  end
end